#!/bin/bash

schematics=`ls ../../{motor,jointio,pwm}/pcb/trunk/*.sch ../../power/pcb/branch/0910/PWR1.sch`

# Check we're being run from the right place:
for sch in $schematics
do
    if [ ! -f $sch ]
	then
	echo Schematic file "$sch" not found.
	echo This script must be run from within a full checkout of /boards.
    fi

    sr pcb_lint $sch
    if [ $? != 0 ]
	then
	echo pcb_lint failed on `basename $sch` -- aborting.
	exit 1
    fi
done

[ -f gerbers ] && rm -rf gerbers
mkdir gerbers

# Generate BOMs and gerbers
for sch in $schematics
do
    d=`dirname $sch`
    make -C $d bom gerbers || ( echo fail -- see above && exit 1 ; )

    gd=gerbers/`basename $sch .sch`
    mkdir $gd

    cp $d/bom.htm $gd
    cp $d/gerbers/* $gd
done


