#!/bin/bash
NUM_BOARDS=20
schematics=`ls ../../{motor,jointio,pwm}/pcb/trunk/*.sch ../../power/pcb/branch/0910/PWR1.sch`
with_num=""

# Check we're being run from the right place:
for sch in $schematics
do
    if [ ! -f $sch ]
	then
	echo Schematic file "$sch" not found.
	echo This script must be run from within a full checkout of /boards.
    fi

    sr pcb_lint $sch
    if [ $? != 0 ]
	then
	echo pcb_lint failed on `basename $sch` -- aborting.
	exit 1
    fi

    with_num="$with_num -$NUM_BOARDS $sch"
done

# Check stock:
echo '*** Stock checking ***'
sr stockcheck $with_num
