<?php
/*This function takes in the file name an retruns it, without the extension */
function returnFileName($nameoffile)
{
	$nameoffile = substr($nameoffile, 0, strlen($nameoffile)-4);
	return $nameoffile;
}

/* This function returns the extension of a file name */
function returnExtension($string)
{
	return(strtolower(substr($string, strlen($string) - 3)));
}

	//prep the vars
	$i = $no = $debug = $fast = 0;
	$yes = 1;

if (!empty($_GET))
	extract($_GET, EXTR_OVERWRITE);

$date = date("l j F", strtotime("+$i day", strtotime("28 September 2007")));

if($no)
	$yes = 0;

$image_array = array("Autumn0.jpg","Autumn1.jpg","Autumn2.jpg","Autumn3.jpg","Autumn4.jpg",
			"Autumn5.jpg","Autumn6.jpg","Autumn7.jpg","Autumn8.jpg","Autumn9.jpg","Autumn10.jpg",
			"Winter0.jpg","Xmas1.gif","Winter1.jpg","Winter2.jpg","Exam0.jpg","Find_X.jpg","Exam1.jpg",
			"Spring0.jpg","Spring1.jpg","Half_Term.jpg","Exam_Results.gif","Spring2.jpg","Spring3.jpg",
			"Spring4.jpg","Easter.jpg","Spring5.jpg","Spring6.jpg","Spring7.jpg","Spring8.jpg");

$image = $image_array[floor($i/7)];

switch ($i)
{
	case 0:
		$date .= " (Today)";
		break;
	case 18:
		$date .= " (Halloween)";
		$image = "Halloween.jpg";
		break;
	case 87:
		$date .= " (Christmas Eve)";
		$image = "Xmas_Eve.jpg";
		break;
	case 88:
		$date .= " (Christmas Day)";
		$image = "Xmas_Day.gif";
		break;
	case 89:
		$date .= " (Boxing Day)";
		$image = "Xmas_Day.gif";
		break;
	case 94:
		$date .= " (New Year's Eve)";
		$image = "NY_Eve.jpg";
		break;
	case 95:
		$date .= " (New Year's Day)";
		$image = "NY_Day.jpg";
		break;
	case 130:
		$date .= " (Pancake Day)";
		$image = "Pancake.jpg";
		break;
	case 177:
		$date .= " (Easter Day)";
		$image = "Easter_Day.jpg";
		break;
	case 205:
		$date .= " (Competition Day)";
		$image = "Competition.jpg";
		break;
}

//	add the " (Custom)" generated by the resize tool
//	$image =  returnFileName($image)." (Custom).".returnExtension($image);

//	find the size of the image
//	spit: the width and height of the image

	list($width, $height, $type, $attr) = getimagesize($image);

$then	= strtotime("28 September 2007 14:00:00");
$now	= strtotime("now");
$time_left	= $then - $now;

$time_per_slide = round($time_left / 206);

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?	$i++;
if(!$no && $i<206)
{
?>	<meta http-equiv="REFRESH" content="<?php echo ($fast ? 1 : $time_per_slide) ?>; URL=?i=<?php echo $i.($fast ? "&fast=1" : "") ?>" /><? }//	One Day is 21 seconds
?>	
	<title>Six Months in 1 Hour</title>
	<link rel="stylesheet" type="text/css" href="6style.css"/>
	<script type="text/javascript">
	function make_it_fit_js(width, height)
	{
		Brw_width	= document.documentElement.clientWidth - 10;	//just in case
		Brw_height	= document.documentElement.clientHeight - 180;	//not forgetting the header bit
		Brw_ratio	= Brw_width / Brw_height;
		ratio = width / height;
		if(Brw_ratio > ratio)	//then the window is wider and we make the height fit
		{
			Img_height	= Brw_height;
			Img_width	= ratio * Img_height;
		}
		else	// the image is wider and we make the height fit
		{
			Img_width	= Brw_width;
			Img_height	= Img_width / ratio;
		}
		document.write(			"<img src=\"<?php echo "$image"?>\"");
		document.write(" style=\"width: " + Img_width + "px; height: " + Img_height + "px\"");
		document.write(" title=\"\" alt=\"\" />");
	}
	</script>
</head>
<body>
<div id="wrapper">
	<div id="page_title">
	<?php if($debug)
			echo "\$time_left=$time_left,	\$time_per_slide=$time_per_slide,	\$then=$then,	\$now=$now,	[floor(\$i/7)]=".floor($i/7);?>
		<table class="head1">
			<tr>
				<td class="left" style="width: 170px;">
				<img src="SRobo_Logo.png" title="" style="width: 170px; height: 163px;" alt="" />
				</td>
				<td class="center">
				<h3 class="center"><?php echo $date ?></h3>
				<br />
				<? if($no) {?><a href="?<? echo htmlspecialchars("no=1&i=".($i-2).($fast ? "&fast=1" : "")) ?>" title="">Previous</a>&nbsp;&nbsp;&nbsp;<? } ?>
				<a href="?<? echo htmlspecialchars("no=$yes&i=".(!$no ? ($i-1) : $i).($fast ? "&fast=1" : "")) ?>" title=""><? echo ($no ? "Continue" : "Pause") ?></a>
				<? if($no) {?>&nbsp;&nbsp;&nbsp;<a href="?<? echo htmlspecialchars("no=1&i=$i".($fast ? "&fast=1" : "")) ?>" title="">Next</a><? } ?>
				</td>
				<td class="right" style="width: 210px;">
				<img src="SRobo1.png" title="" style="width: 203px; height: 73px; margin-right: 7px;" alt="" />
				</td>
			</tr>
		</table>
	</div>
	<div id="page_main">
		<script type="text/javascript">
			make_it_fit_js(<? echo "$width, $height" ?>);
		</script>
	</div>	
</div>
</body>
</html>