Building is fairly simple.  Follow these steps:
 1) Run "make defconfig".
 2) Run "make"
    The next thing you do depends on how many cores you have, how fast
    they go and how fast your disk is.  Please allow this ASCII art
    diagram to explain:

    More Cores   		^  * Blink
    Faster Disk			|   
				|  * Get some Coffee.
				|   
    Slow Single Processor	|  * Watch a film.
    Hard Disk			|  
				|
    Floppy Disk			|  * Make a film describing what
				|    you'd like to do with this
				|    software.  Hope that your
				|    descendants watch it.
    
