assembly.pdf: assembly.tex glossary.tex power-assembly.tex motor-assembly.tex pwm-assembly.tex jointio-assembly.tex
	pdflatex assembly.tex
	pdflatex assembly.tex

clean:
	rm -rf *.aux *.pdf *.dvi *.log
