<?php
/*This function takes in the file name an retruns it, without the extension */
function returnFileName($nameoffile)
{
	$nameoffile = substr($nameoffile, 0, strlen($nameoffile)-4);
	return $nameoffile;
}

/* This function returns the extension of a file name */
function returnExtension($string)
{
	return(strtolower(substr($string, strlen($string) - 3)));
}

if (!empty($_GET))
	extract($_GET, EXTR_OVERWRITE);

if(!isset($i))
	$i = 0;

$date = date("l j F", strtotime("+$i day", strtotime("28 September 2007")));

$yes = 1;
if($no)
	$yes = 0;

switch ($i)
{
	case 0:
		$date .= " (Today)";
		break;
	case 87:
		$date .= " (Christmas Eve)";
		break;
	case 88:
		$date .= " (Christmas Day)";
		break;
	case 89:
		$date .= " (Boxing Day)";
		break;
	case 94:
		$date .= " (New Year's Eve)";
		break;
	case 95:
		$date .= " (New Year's Day)";
		break;
	case 130:
		$date .= " (Pancake Day)";
		break;
	case 177:
		$date .= " (Easter Day)";
		break;
	case 205:
		$date .= " (Competition Day)";
		break;
}

$image_array = array("","","","","","","","Autumn7.jpg","Winter0.jpg","Winter1.jpg","Winter2.jpg",
			"Winter3.jpg","Xmas1.gif","Spring1.jpg","","","",);

$image = $image_array[floor($i/7)];

//	add the " (Custom)" generated by the resize tool
//	$image =  returnFileName($image)." (Custom).".returnExtension($image);

//	find the size of the image
//	spit: the width and height of the image

	list($width, $height, $type, $attr) = getimagesize($image);

$then	= strtotime("28 September 2007 14:00:00");
$now	= strtotime("now");
$time_left	= $then - $now;

$time_per_slide = round($time_left / 206);

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<?	$i++;
if(!$no)
{
?>	<meta http-equiv="REFRESH" content="1; URL=?i=<?php echo $i; ?>" /><? }//	One Day is 21 seconds
?>	
	<title>Six Months in 1 Hour</title>
	<link rel="stylesheet" type="text/css" href="6style.css"/>
	<script type="text/javascript">
	function make_it_fit_js(width, height)
	{
		Brw_width	= document.documentElement.clientWidth - 10;	//just in case
		Brw_height	= document.documentElement.clientHeight - 180;	//not forgetting the header bit
		Brw_ratio	= Brw_width / Brw_height;
		ratio = width / height;
		if(Brw_ratio > ratio)	//then the window is wider and we make the height fit
		{
			Img_height	= Brw_height;
			Img_width	= ratio * Img_height;
		}
		else	// the image is wider and we make the height fit
		{
			Img_width	= Brw_width;
			Img_height	= Img_width / ratio;
		}
		document.write(" style=\"width: " + Img_width + "px; height: " + Img_height + "px\"");
//		alert(Brw_width + ", " + Brw_height);
	}
	</script>
</head>
<body>
<div id="wrapper">
	<div id="page_title">
	<?php if($debug)
			echo "\$time_left=$time_left,	\$time_per_slide=$time_per_slide,	\$then=$then,	\$now=$now";?>
		<table class="head1">
			<tr>
				<td class="left" style="width: 170px;">
				<img src="SRobo_Logo.png" title="" style="width: 170px; height: 163px;" alt="" />
				</td>
				<td class="center">
				<h3 class="center"><?php echo $date ?></h3>
				<br />
				<? if($no) {?><a href="?<? echo "no=1&i=".($i-2) ?>" title="">Previous</a>&nbsp;&nbsp;&nbsp;<? } ?>
				<a href="?<? echo "no=$yes&i=".(!$no ? ($i-1) : $i) ?>" title=""><? echo ($no ? "Continue" : "Pause") ?></a>
				<? if($no) {?>&nbsp;&nbsp;&nbsp;<a href="?<? echo "no=1&i=$i" ?>" title="">Next</a><? } ?>
				</td>
				<td class="right" style="width: 210px;">
				<img src="SRobo1.png" title="" style="width: 203px; height: 73px; margin-right: 7px;" alt="" />
				</td>
			</tr>
		</table>
	</div>
	<div id="page_main">
		<script type="text/javascript">
			document.write(			"<img src=\"<?php echo "$image"?>\"");
			make_it_fit_js(<? echo "$width, $height" ?>);
			document.write(" title=\"\" alt=\"\" />");
		</script>
	</div>	
</div>
</body>
</html>